definitions:
  api.AverageRangePriceRequest:
    properties:
      from_time_stamp:
        type: integer
      to_time_stamp:
        type: integer
      token:
        type: string
    required:
    - from_time_stamp
    - to_time_stamp
    - token
    type: object
info:
  contact: {}
paths:
  /lastPrice/{token}:
    get:
      parameters:
      - description: token
        in: path
        name: token
        required: true
        type: string
      responses:
        "200":
          description: ""
      summary: Get Latest Price
      tags:
      - Price
  /lastPrice/{token}/{timestamp}:
    get:
      parameters:
      - description: token
        in: path
        name: token
        required: true
        type: string
      - description: timestamp
        in: path
        name: timestamp
        required: true
        type: integer
      responses:
        "200":
          description: ""
      summary: Get Latest Price by timestamp
      tags:
      - Price
  /rangePrice:
    post:
      description: Get average price for the time range. If not exist will add into
        database for cache
      parameters:
      - description: Range Price
        in: body
        name: rangePrice
        required: true
        schema:
          $ref: '#/definitions/api.AverageRangePriceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Get average price for the time range with specific token
      tags:
      - Price
swagger: "2.0"
